# Generated by Django 3.2.7 on 2021-12-14 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 17, 47, 58, 760445)),
        ),
    ]
