# Generated by Django 3.2.7 on 2021-12-28 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_crud', '0005_alter_crud_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 28, 17, 6, 11, 452096)),
        ),
    ]
