# Generated by Django 4.0 on 2021-12-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='gender',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
