# Generated by Django 3.2.7 on 2021-12-25 11:24

import FileUpload.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('filepath', models.FileField(upload_to='files/', validators=[FileUpload.validators.validate_file_size], verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 25, 16, 54, 9, 818627)),
        ),
    ]
