# Generated by Django 3.2.7 on 2021-12-28 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0003_alter_fileupload_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 28, 17, 59, 43, 157574)),
        ),
    ]
