# Generated by Django 3.2.7 on 2021-12-18 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('hobby', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 18, 16, 56, 56, 791594))),
            ],
        ),
    ]
