# Generated by Django 3.2.7 on 2021-12-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 21, 17, 4, 2, 229686)),
        ),
    ]
