# Generated by Django 3.2.7 on 2021-12-28 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_crud', '0003_alter_complex_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 28, 17, 6, 11, 468823)),
        ),
    ]
